# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ratimics/develop/cgame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ratimics/develop/cgame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ratimics/develop/cgame/CMakeFiles /Users/ratimics/develop/cgame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ratimics/develop/cgame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cgame

# Build rule for target.
cgame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cgame
.PHONY : cgame

# fast build rule for target.
cgame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgame.dir/build.make CMakeFiles/cgame.dir/build
.PHONY : cgame/fast

#=============================================================================
# Target rules for targets named hidapi

# Build rule for target.
hidapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hidapi
.PHONY : hidapi

# fast build rule for target.
hidapi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hidapi.dir/build.make CMakeFiles/hidapi.dir/build
.PHONY : hidapi/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named look_target

# Build rule for target.
look_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 look_target
.PHONY : look_target

# fast build rule for target.
look_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/look_target.dir/build.make CMakeFiles/look_target.dir/build
.PHONY : look_target/fast

#=============================================================================
# Target rules for targets named physics

# Build rule for target.
physics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 physics
.PHONY : physics

# fast build rule for target.
physics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/build
.PHONY : physics/fast

#=============================================================================
# Target rules for targets named collision

# Build rule for target.
collision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 collision
.PHONY : collision

# fast build rule for target.
collision/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/collision.dir/build.make CMakeFiles/collision.dir/build
.PHONY : collision/fast

#=============================================================================
# Target rules for targets named ai

# Build rule for target.
ai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ai
.PHONY : ai

# fast build rule for target.
ai/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/build
.PHONY : ai/fast

#=============================================================================
# Target rules for targets named camera_system

# Build rule for target.
camera_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 camera_system
.PHONY : camera_system

# fast build rule for target.
camera_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera_system.dir/build.make CMakeFiles/camera_system.dir/build
.PHONY : camera_system/fast

#=============================================================================
# Target rules for targets named lod

# Build rule for target.
lod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lod
.PHONY : lod

# fast build rule for target.
lod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lod.dir/build.make CMakeFiles/lod.dir/build
.PHONY : lod/fast

#=============================================================================
# Target rules for targets named performance

# Build rule for target.
performance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 performance
.PHONY : performance

# fast build rule for target.
performance/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/performance.dir/build.make CMakeFiles/performance.dir/build
.PHONY : performance/fast

#=============================================================================
# Target rules for targets named memory

# Build rule for target.
memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory
.PHONY : memory

# fast build rule for target.
memory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory.dir/build.make CMakeFiles/memory.dir/build
.PHONY : memory/fast

#=============================================================================
# Target rules for targets named material

# Build rule for target.
material: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 material
.PHONY : material

# fast build rule for target.
material/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/material.dir/build.make CMakeFiles/material.dir/build
.PHONY : material/fast

#=============================================================================
# Target rules for targets named gamepad

# Build rule for target.
gamepad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamepad
.PHONY : gamepad

# fast build rule for target.
gamepad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamepad.dir/build.make CMakeFiles/gamepad.dir/build
.PHONY : gamepad/fast

#=============================================================================
# Target rules for targets named input_processing

# Build rule for target.
input_processing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 input_processing
.PHONY : input_processing

# fast build rule for target.
input_processing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input_processing.dir/build.make CMakeFiles/input_processing.dir/build
.PHONY : input_processing/fast

#=============================================================================
# Target rules for targets named input

# Build rule for target.
input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 input
.PHONY : input

# fast build rule for target.
input/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input.dir/build.make CMakeFiles/input.dir/build
.PHONY : input/fast

#=============================================================================
# Target rules for targets named thrusters

# Build rule for target.
thrusters: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thrusters
.PHONY : thrusters

# fast build rule for target.
thrusters/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thrusters.dir/build.make CMakeFiles/thrusters.dir/build
.PHONY : thrusters/fast

#=============================================================================
# Target rules for targets named control

# Build rule for target.
control: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 control
.PHONY : control

# fast build rule for target.
control/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/build
.PHONY : control/fast

#=============================================================================
# Target rules for targets named systems

# Build rule for target.
systems: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 systems
.PHONY : systems

# fast build rule for target.
systems/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/systems.dir/build.make CMakeFiles/systems.dir/build
.PHONY : systems/fast

#=============================================================================
# Target rules for targets named gpu_resources

# Build rule for target.
gpu_resources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpu_resources
.PHONY : gpu_resources

# fast build rule for target.
gpu_resources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_resources.dir/build.make CMakeFiles/gpu_resources.dir/build
.PHONY : gpu_resources/fast

#=============================================================================
# Target rules for targets named asset_loader

# Build rule for target.
asset_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asset_loader
.PHONY : asset_loader

# fast build rule for target.
asset_loader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/build
.PHONY : asset_loader/fast

#=============================================================================
# Target rules for targets named assets

# Build rule for target.
assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assets
.PHONY : assets

# fast build rule for target.
assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assets.dir/build.make CMakeFiles/assets.dir/build
.PHONY : assets/fast

#=============================================================================
# Target rules for targets named data

# Build rule for target.
data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data
.PHONY : data

# fast build rule for target.
data/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/build
.PHONY : data/fast

#=============================================================================
# Target rules for targets named scene_state

# Build rule for target.
scene_state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scene_state
.PHONY : scene_state

# fast build rule for target.
scene_state/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_state.dir/build.make CMakeFiles/scene_state.dir/build
.PHONY : scene_state/fast

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named logo_scene_script

# Build rule for target.
logo_scene_script: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logo_scene_script
.PHONY : logo_scene_script

# fast build rule for target.
logo_scene_script/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logo_scene_script.dir/build.make CMakeFiles/logo_scene_script.dir/build
.PHONY : logo_scene_script/fast

#=============================================================================
# Target rules for targets named derelict_navigation_scene_script

# Build rule for target.
derelict_navigation_scene_script: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 derelict_navigation_scene_script
.PHONY : derelict_navigation_scene_script

# fast build rule for target.
derelict_navigation_scene_script/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/derelict_navigation_scene_script.dir/build.make CMakeFiles/derelict_navigation_scene_script.dir/build
.PHONY : derelict_navigation_scene_script/fast

#=============================================================================
# Target rules for targets named flight_test_scene_script

# Build rule for target.
flight_test_scene_script: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flight_test_scene_script
.PHONY : flight_test_scene_script

# fast build rule for target.
flight_test_scene_script/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_test_scene_script.dir/build.make CMakeFiles/flight_test_scene_script.dir/build
.PHONY : flight_test_scene_script/fast

#=============================================================================
# Target rules for targets named scene_selector_scene_script

# Build rule for target.
scene_selector_scene_script: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scene_selector_scene_script
.PHONY : scene_selector_scene_script

# fast build rule for target.
scene_selector_scene_script/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_selector_scene_script.dir/build.make CMakeFiles/scene_selector_scene_script.dir/build
.PHONY : scene_selector_scene_script/fast

#=============================================================================
# Target rules for targets named thruster_test_scene_script

# Build rule for target.
thruster_test_scene_script: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thruster_test_scene_script
.PHONY : thruster_test_scene_script

# fast build rule for target.
thruster_test_scene_script/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thruster_test_scene_script.dir/build.make CMakeFiles/thruster_test_scene_script.dir/build
.PHONY : thruster_test_scene_script/fast

#=============================================================================
# Target rules for targets named scene_script

# Build rule for target.
scene_script: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scene_script
.PHONY : scene_script

# fast build rule for target.
scene_script/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_script.dir/build.make CMakeFiles/scene_script.dir/build
.PHONY : scene_script/fast

#=============================================================================
# Target rules for targets named graphics_api

# Build rule for target.
graphics_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphics_api
.PHONY : graphics_api

# fast build rule for target.
graphics_api/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics_api.dir/build.make CMakeFiles/graphics_api.dir/build
.PHONY : graphics_api/fast

#=============================================================================
# Target rules for targets named render_camera

# Build rule for target.
render_camera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_camera
.PHONY : render_camera

# fast build rule for target.
render_camera/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_camera.dir/build.make CMakeFiles/render_camera.dir/build
.PHONY : render_camera/fast

#=============================================================================
# Target rules for targets named render_mesh

# Build rule for target.
render_mesh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_mesh
.PHONY : render_mesh

# fast build rule for target.
render_mesh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_mesh.dir/build.make CMakeFiles/render_mesh.dir/build
.PHONY : render_mesh/fast

#=============================================================================
# Target rules for targets named render_lighting

# Build rule for target.
render_lighting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_lighting
.PHONY : render_lighting

# fast build rule for target.
render_lighting/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_lighting.dir/build.make CMakeFiles/render_lighting.dir/build
.PHONY : render_lighting/fast

#=============================================================================
# Target rules for targets named render_3d

# Build rule for target.
render_3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_3d
.PHONY : render_3d

# fast build rule for target.
render_3d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_3d.dir/build.make CMakeFiles/render_3d.dir/build
.PHONY : render_3d/fast

#=============================================================================
# Target rules for targets named ui_api

# Build rule for target.
ui_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_api
.PHONY : ui_api

# fast build rule for target.
ui_api/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_api.dir/build.make CMakeFiles/ui_api.dir/build
.PHONY : ui_api/fast

#=============================================================================
# Target rules for targets named ui_components

# Build rule for target.
ui_components: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_components
.PHONY : ui_components

# fast build rule for target.
ui_components/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_components.dir/build.make CMakeFiles/ui_components.dir/build
.PHONY : ui_components/fast

#=============================================================================
# Target rules for targets named ui_scene

# Build rule for target.
ui_scene: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_scene
.PHONY : ui_scene

# fast build rule for target.
ui_scene/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_scene.dir/build.make CMakeFiles/ui_scene.dir/build
.PHONY : ui_scene/fast

#=============================================================================
# Target rules for targets named ui_adaptive_controls

# Build rule for target.
ui_adaptive_controls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_adaptive_controls
.PHONY : ui_adaptive_controls

# fast build rule for target.
ui_adaptive_controls/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_adaptive_controls.dir/build.make CMakeFiles/ui_adaptive_controls.dir/build
.PHONY : ui_adaptive_controls/fast

#=============================================================================
# Target rules for targets named hud_system

# Build rule for target.
hud_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hud_system
.PHONY : hud_system

# fast build rule for target.
hud_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hud_system.dir/build.make CMakeFiles/hud_system.dir/build
.PHONY : hud_system/fast

#=============================================================================
# Target rules for targets named ui_navigation_menu

# Build rule for target.
ui_navigation_menu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_navigation_menu
.PHONY : ui_navigation_menu

# fast build rule for target.
ui_navigation_menu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/build
.PHONY : ui_navigation_menu/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named compile_assets

# Build rule for target.
compile_assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_assets
.PHONY : compile_assets

# fast build rule for target.
compile_assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compile_assets.dir/build.make CMakeFiles/compile_assets.dir/build
.PHONY : compile_assets/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-assets

# Build rule for target.
clean-assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-assets
.PHONY : clean-assets

# fast build rule for target.
clean-assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-assets.dir/build.make CMakeFiles/clean-assets.dir/build
.PHONY : clean-assets/fast

#=============================================================================
# Target rules for targets named profile

# Build rule for target.
profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 profile
.PHONY : profile

# fast build rule for target.
profile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile.dir/build.make CMakeFiles/profile.dir/build
.PHONY : profile/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named test_cmake-core_test_components

# Build rule for target.
test_cmake-core_test_components: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-core_test_components
.PHONY : test_cmake-core_test_components

# fast build rule for target.
test_cmake-core_test_components/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-core_test_components.dir/build.make tests/CMakeFiles/test_cmake-core_test_components.dir/build
.PHONY : test_cmake-core_test_components/fast

#=============================================================================
# Target rules for targets named test_cmake-core_test_math

# Build rule for target.
test_cmake-core_test_math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-core_test_math
.PHONY : test_cmake-core_test_math

# fast build rule for target.
test_cmake-core_test_math/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-core_test_math.dir/build.make tests/CMakeFiles/test_cmake-core_test_math.dir/build
.PHONY : test_cmake-core_test_math/fast

#=============================================================================
# Target rules for targets named test_cmake-core_test_world

# Build rule for target.
test_cmake-core_test_world: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-core_test_world
.PHONY : test_cmake-core_test_world

# fast build rule for target.
test_cmake-core_test_world/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-core_test_world.dir/build.make tests/CMakeFiles/test_cmake-core_test_world.dir/build
.PHONY : test_cmake-core_test_world/fast

#=============================================================================
# Target rules for targets named test_cmake-rendering

# Build rule for target.
test_cmake-rendering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-rendering
.PHONY : test_cmake-rendering

# fast build rule for target.
test_cmake-rendering/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-rendering.dir/build.make tests/CMakeFiles/test_cmake-rendering.dir/build
.PHONY : test_cmake-rendering/fast

#=============================================================================
# Target rules for targets named test_cmake-ui

# Build rule for target.
test_cmake-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-ui
.PHONY : test_cmake-ui

# fast build rule for target.
test_cmake-ui/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-ui.dir/build.make tests/CMakeFiles/test_cmake-ui.dir/build
.PHONY : test_cmake-ui/fast

#=============================================================================
# Target rules for targets named test_cmake-integration

# Build rule for target.
test_cmake-integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-integration
.PHONY : test_cmake-integration

# fast build rule for target.
test_cmake-integration/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-integration.dir/build.make tests/CMakeFiles/test_cmake-integration.dir/build
.PHONY : test_cmake-integration/fast

#=============================================================================
# Target rules for targets named test_cmake-performance_test_memory_isolated

# Build rule for target.
test_cmake-performance_test_memory_isolated: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-performance_test_memory_isolated
.PHONY : test_cmake-performance_test_memory_isolated

# fast build rule for target.
test_cmake-performance_test_memory_isolated/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-performance_test_memory_isolated.dir/build.make tests/CMakeFiles/test_cmake-performance_test_memory_isolated.dir/build
.PHONY : test_cmake-performance_test_memory_isolated/fast

#=============================================================================
# Target rules for targets named test_cmake-performance_test_memory_perf

# Build rule for target.
test_cmake-performance_test_memory_perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-performance_test_memory_perf
.PHONY : test_cmake-performance_test_memory_perf

# fast build rule for target.
test_cmake-performance_test_memory_perf/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-performance_test_memory_perf.dir/build.make tests/CMakeFiles/test_cmake-performance_test_memory_perf.dir/build
.PHONY : test_cmake-performance_test_memory_perf/fast

#=============================================================================
# Target rules for targets named test_cmake-performance_test_performance_critical

# Build rule for target.
test_cmake-performance_test_performance_critical: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-performance_test_performance_critical
.PHONY : test_cmake-performance_test_performance_critical

# fast build rule for target.
test_cmake-performance_test_performance_critical/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-performance_test_performance_critical.dir/build.make tests/CMakeFiles/test_cmake-performance_test_performance_critical.dir/build
.PHONY : test_cmake-performance_test_performance_critical/fast

#=============================================================================
# Target rules for targets named test_cmake-performance_test_performance_simple

# Build rule for target.
test_cmake-performance_test_performance_simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmake-performance_test_performance_simple
.PHONY : test_cmake-performance_test_performance_simple

# fast build rule for target.
test_cmake-performance_test_performance_simple/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmake-performance_test_performance_simple.dir/build.make tests/CMakeFiles/test_cmake-performance_test_performance_simple.dir/build
.PHONY : test_cmake-performance_test_performance_simple/fast

#=============================================================================
# Target rules for targets named run-ctest

# Build rule for target.
run-ctest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run-ctest
.PHONY : run-ctest

# fast build rule for target.
run-ctest/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run-ctest.dir/build.make tests/CMakeFiles/run-ctest.dir/build
.PHONY : run-ctest/fast

src/asset_loader/asset_loader_index.o: src/asset_loader/asset_loader_index.c.o
.PHONY : src/asset_loader/asset_loader_index.o

# target to build an object file
src/asset_loader/asset_loader_index.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_index.c.o
.PHONY : src/asset_loader/asset_loader_index.c.o

src/asset_loader/asset_loader_index.i: src/asset_loader/asset_loader_index.c.i
.PHONY : src/asset_loader/asset_loader_index.i

# target to preprocess a source file
src/asset_loader/asset_loader_index.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_index.c.i
.PHONY : src/asset_loader/asset_loader_index.c.i

src/asset_loader/asset_loader_index.s: src/asset_loader/asset_loader_index.c.s
.PHONY : src/asset_loader/asset_loader_index.s

# target to generate assembly for a file
src/asset_loader/asset_loader_index.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_index.c.s
.PHONY : src/asset_loader/asset_loader_index.c.s

src/asset_loader/asset_loader_material.o: src/asset_loader/asset_loader_material.c.o
.PHONY : src/asset_loader/asset_loader_material.o

# target to build an object file
src/asset_loader/asset_loader_material.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_material.c.o
.PHONY : src/asset_loader/asset_loader_material.c.o

src/asset_loader/asset_loader_material.i: src/asset_loader/asset_loader_material.c.i
.PHONY : src/asset_loader/asset_loader_material.i

# target to preprocess a source file
src/asset_loader/asset_loader_material.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_material.c.i
.PHONY : src/asset_loader/asset_loader_material.c.i

src/asset_loader/asset_loader_material.s: src/asset_loader/asset_loader_material.c.s
.PHONY : src/asset_loader/asset_loader_material.s

# target to generate assembly for a file
src/asset_loader/asset_loader_material.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_material.c.s
.PHONY : src/asset_loader/asset_loader_material.c.s

src/asset_loader/asset_loader_mesh.o: src/asset_loader/asset_loader_mesh.c.o
.PHONY : src/asset_loader/asset_loader_mesh.o

# target to build an object file
src/asset_loader/asset_loader_mesh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_mesh.c.o
.PHONY : src/asset_loader/asset_loader_mesh.c.o

src/asset_loader/asset_loader_mesh.i: src/asset_loader/asset_loader_mesh.c.i
.PHONY : src/asset_loader/asset_loader_mesh.i

# target to preprocess a source file
src/asset_loader/asset_loader_mesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_mesh.c.i
.PHONY : src/asset_loader/asset_loader_mesh.c.i

src/asset_loader/asset_loader_mesh.s: src/asset_loader/asset_loader_mesh.c.s
.PHONY : src/asset_loader/asset_loader_mesh.s

# target to generate assembly for a file
src/asset_loader/asset_loader_mesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asset_loader.dir/build.make CMakeFiles/asset_loader.dir/src/asset_loader/asset_loader_mesh.c.s
.PHONY : src/asset_loader/asset_loader_mesh.c.s

src/assets.o: src/assets.c.o
.PHONY : src/assets.o

# target to build an object file
src/assets.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assets.dir/build.make CMakeFiles/assets.dir/src/assets.c.o
.PHONY : src/assets.c.o

src/assets.i: src/assets.c.i
.PHONY : src/assets.i

# target to preprocess a source file
src/assets.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assets.dir/build.make CMakeFiles/assets.dir/src/assets.c.i
.PHONY : src/assets.c.i

src/assets.s: src/assets.c.s
.PHONY : src/assets.s

# target to generate assembly for a file
src/assets.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assets.dir/build.make CMakeFiles/assets.dir/src/assets.c.s
.PHONY : src/assets.c.s

src/component/look_target.o: src/component/look_target.c.o
.PHONY : src/component/look_target.o

# target to build an object file
src/component/look_target.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/look_target.dir/build.make CMakeFiles/look_target.dir/src/component/look_target.c.o
.PHONY : src/component/look_target.c.o

src/component/look_target.i: src/component/look_target.c.i
.PHONY : src/component/look_target.i

# target to preprocess a source file
src/component/look_target.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/look_target.dir/build.make CMakeFiles/look_target.dir/src/component/look_target.c.i
.PHONY : src/component/look_target.c.i

src/component/look_target.s: src/component/look_target.c.s
.PHONY : src/component/look_target.s

# target to generate assembly for a file
src/component/look_target.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/look_target.dir/build.make CMakeFiles/look_target.dir/src/component/look_target.c.s
.PHONY : src/component/look_target.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/src/config.c.s
.PHONY : src/config.c.s

src/core.o: src/core.c.o
.PHONY : src/core.o

# target to build an object file
src/core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core.c.o
.PHONY : src/core.c.o

src/core.i: src/core.c.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core.c.i
.PHONY : src/core.c.i

src/core.s: src/core.c.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core.c.s
.PHONY : src/core.c.s

src/data.o: src/data.c.o
.PHONY : src/data.o

# target to build an object file
src/data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/data.c.o
.PHONY : src/data.c.o

src/data.i: src/data.c.i
.PHONY : src/data.i

# target to preprocess a source file
src/data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/data.c.i
.PHONY : src/data.c.i

src/data.s: src/data.c.s
.PHONY : src/data.s

# target to generate assembly for a file
src/data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/data.c.s
.PHONY : src/data.c.s

src/gpu_resources.o: src/gpu_resources.c.o
.PHONY : src/gpu_resources.o

# target to build an object file
src/gpu_resources.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_resources.dir/build.make CMakeFiles/gpu_resources.dir/src/gpu_resources.c.o
.PHONY : src/gpu_resources.c.o

src/gpu_resources.i: src/gpu_resources.c.i
.PHONY : src/gpu_resources.i

# target to preprocess a source file
src/gpu_resources.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_resources.dir/build.make CMakeFiles/gpu_resources.dir/src/gpu_resources.c.i
.PHONY : src/gpu_resources.c.i

src/gpu_resources.s: src/gpu_resources.c.s
.PHONY : src/gpu_resources.s

# target to generate assembly for a file
src/gpu_resources.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_resources.dir/build.make CMakeFiles/gpu_resources.dir/src/gpu_resources.c.s
.PHONY : src/gpu_resources.c.s

src/graphics_api.o: src/graphics_api.c.o
.PHONY : src/graphics_api.o

# target to build an object file
src/graphics_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics_api.dir/build.make CMakeFiles/graphics_api.dir/src/graphics_api.c.o
.PHONY : src/graphics_api.c.o

src/graphics_api.i: src/graphics_api.c.i
.PHONY : src/graphics_api.i

# target to preprocess a source file
src/graphics_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics_api.dir/build.make CMakeFiles/graphics_api.dir/src/graphics_api.c.i
.PHONY : src/graphics_api.c.i

src/graphics_api.s: src/graphics_api.c.s
.PHONY : src/graphics_api.s

# target to generate assembly for a file
src/graphics_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics_api.dir/build.make CMakeFiles/graphics_api.dir/src/graphics_api.c.s
.PHONY : src/graphics_api.c.s

src/hud_system.o: src/hud_system.c.o
.PHONY : src/hud_system.o

# target to build an object file
src/hud_system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hud_system.dir/build.make CMakeFiles/hud_system.dir/src/hud_system.c.o
.PHONY : src/hud_system.c.o

src/hud_system.i: src/hud_system.c.i
.PHONY : src/hud_system.i

# target to preprocess a source file
src/hud_system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hud_system.dir/build.make CMakeFiles/hud_system.dir/src/hud_system.c.i
.PHONY : src/hud_system.c.i

src/hud_system.s: src/hud_system.c.s
.PHONY : src/hud_system.s

# target to generate assembly for a file
src/hud_system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hud_system.dir/build.make CMakeFiles/hud_system.dir/src/hud_system.c.s
.PHONY : src/hud_system.c.s

src/input_processing.o: src/input_processing.c.o
.PHONY : src/input_processing.o

# target to build an object file
src/input_processing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input_processing.dir/build.make CMakeFiles/input_processing.dir/src/input_processing.c.o
.PHONY : src/input_processing.c.o

src/input_processing.i: src/input_processing.c.i
.PHONY : src/input_processing.i

# target to preprocess a source file
src/input_processing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input_processing.dir/build.make CMakeFiles/input_processing.dir/src/input_processing.c.i
.PHONY : src/input_processing.c.i

src/input_processing.s: src/input_processing.c.s
.PHONY : src/input_processing.s

# target to generate assembly for a file
src/input_processing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input_processing.dir/build.make CMakeFiles/input_processing.dir/src/input_processing.c.s
.PHONY : src/input_processing.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgame.dir/build.make CMakeFiles/cgame.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgame.dir/build.make CMakeFiles/cgame.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgame.dir/build.make CMakeFiles/cgame.dir/src/main.c.s
.PHONY : src/main.c.s

src/render_3d.o: src/render_3d.c.o
.PHONY : src/render_3d.o

# target to build an object file
src/render_3d.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_3d.dir/build.make CMakeFiles/render_3d.dir/src/render_3d.c.o
.PHONY : src/render_3d.c.o

src/render_3d.i: src/render_3d.c.i
.PHONY : src/render_3d.i

# target to preprocess a source file
src/render_3d.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_3d.dir/build.make CMakeFiles/render_3d.dir/src/render_3d.c.i
.PHONY : src/render_3d.c.i

src/render_3d.s: src/render_3d.c.s
.PHONY : src/render_3d.s

# target to generate assembly for a file
src/render_3d.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_3d.dir/build.make CMakeFiles/render_3d.dir/src/render_3d.c.s
.PHONY : src/render_3d.c.s

src/render_camera.o: src/render_camera.c.o
.PHONY : src/render_camera.o

# target to build an object file
src/render_camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_camera.dir/build.make CMakeFiles/render_camera.dir/src/render_camera.c.o
.PHONY : src/render_camera.c.o

src/render_camera.i: src/render_camera.c.i
.PHONY : src/render_camera.i

# target to preprocess a source file
src/render_camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_camera.dir/build.make CMakeFiles/render_camera.dir/src/render_camera.c.i
.PHONY : src/render_camera.c.i

src/render_camera.s: src/render_camera.c.s
.PHONY : src/render_camera.s

# target to generate assembly for a file
src/render_camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_camera.dir/build.make CMakeFiles/render_camera.dir/src/render_camera.c.s
.PHONY : src/render_camera.c.s

src/render_lighting.o: src/render_lighting.c.o
.PHONY : src/render_lighting.o

# target to build an object file
src/render_lighting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_lighting.dir/build.make CMakeFiles/render_lighting.dir/src/render_lighting.c.o
.PHONY : src/render_lighting.c.o

src/render_lighting.i: src/render_lighting.c.i
.PHONY : src/render_lighting.i

# target to preprocess a source file
src/render_lighting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_lighting.dir/build.make CMakeFiles/render_lighting.dir/src/render_lighting.c.i
.PHONY : src/render_lighting.c.i

src/render_lighting.s: src/render_lighting.c.s
.PHONY : src/render_lighting.s

# target to generate assembly for a file
src/render_lighting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_lighting.dir/build.make CMakeFiles/render_lighting.dir/src/render_lighting.c.s
.PHONY : src/render_lighting.c.s

src/render_mesh.o: src/render_mesh.c.o
.PHONY : src/render_mesh.o

# target to build an object file
src/render_mesh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_mesh.dir/build.make CMakeFiles/render_mesh.dir/src/render_mesh.c.o
.PHONY : src/render_mesh.c.o

src/render_mesh.i: src/render_mesh.c.i
.PHONY : src/render_mesh.i

# target to preprocess a source file
src/render_mesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_mesh.dir/build.make CMakeFiles/render_mesh.dir/src/render_mesh.c.i
.PHONY : src/render_mesh.c.i

src/render_mesh.s: src/render_mesh.c.s
.PHONY : src/render_mesh.s

# target to generate assembly for a file
src/render_mesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_mesh.dir/build.make CMakeFiles/render_mesh.dir/src/render_mesh.c.s
.PHONY : src/render_mesh.c.s

src/scene_script.o: src/scene_script.c.o
.PHONY : src/scene_script.o

# target to build an object file
src/scene_script.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_script.dir/build.make CMakeFiles/scene_script.dir/src/scene_script.c.o
.PHONY : src/scene_script.c.o

src/scene_script.i: src/scene_script.c.i
.PHONY : src/scene_script.i

# target to preprocess a source file
src/scene_script.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_script.dir/build.make CMakeFiles/scene_script.dir/src/scene_script.c.i
.PHONY : src/scene_script.c.i

src/scene_script.s: src/scene_script.c.s
.PHONY : src/scene_script.s

# target to generate assembly for a file
src/scene_script.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_script.dir/build.make CMakeFiles/scene_script.dir/src/scene_script.c.s
.PHONY : src/scene_script.c.s

src/scene_state.o: src/scene_state.c.o
.PHONY : src/scene_state.o

# target to build an object file
src/scene_state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_state.dir/build.make CMakeFiles/scene_state.dir/src/scene_state.c.o
.PHONY : src/scene_state.c.o

src/scene_state.i: src/scene_state.c.i
.PHONY : src/scene_state.i

# target to preprocess a source file
src/scene_state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_state.dir/build.make CMakeFiles/scene_state.dir/src/scene_state.c.i
.PHONY : src/scene_state.c.i

src/scene_state.s: src/scene_state.c.s
.PHONY : src/scene_state.s

# target to generate assembly for a file
src/scene_state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_state.dir/build.make CMakeFiles/scene_state.dir/src/scene_state.c.s
.PHONY : src/scene_state.c.s

src/scripts/derelict_navigation_scene.o: src/scripts/derelict_navigation_scene.c.o
.PHONY : src/scripts/derelict_navigation_scene.o

# target to build an object file
src/scripts/derelict_navigation_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/derelict_navigation_scene_script.dir/build.make CMakeFiles/derelict_navigation_scene_script.dir/src/scripts/derelict_navigation_scene.c.o
.PHONY : src/scripts/derelict_navigation_scene.c.o

src/scripts/derelict_navigation_scene.i: src/scripts/derelict_navigation_scene.c.i
.PHONY : src/scripts/derelict_navigation_scene.i

# target to preprocess a source file
src/scripts/derelict_navigation_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/derelict_navigation_scene_script.dir/build.make CMakeFiles/derelict_navigation_scene_script.dir/src/scripts/derelict_navigation_scene.c.i
.PHONY : src/scripts/derelict_navigation_scene.c.i

src/scripts/derelict_navigation_scene.s: src/scripts/derelict_navigation_scene.c.s
.PHONY : src/scripts/derelict_navigation_scene.s

# target to generate assembly for a file
src/scripts/derelict_navigation_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/derelict_navigation_scene_script.dir/build.make CMakeFiles/derelict_navigation_scene_script.dir/src/scripts/derelict_navigation_scene.c.s
.PHONY : src/scripts/derelict_navigation_scene.c.s

src/scripts/flight_test_scene.o: src/scripts/flight_test_scene.c.o
.PHONY : src/scripts/flight_test_scene.o

# target to build an object file
src/scripts/flight_test_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_test_scene_script.dir/build.make CMakeFiles/flight_test_scene_script.dir/src/scripts/flight_test_scene.c.o
.PHONY : src/scripts/flight_test_scene.c.o

src/scripts/flight_test_scene.i: src/scripts/flight_test_scene.c.i
.PHONY : src/scripts/flight_test_scene.i

# target to preprocess a source file
src/scripts/flight_test_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_test_scene_script.dir/build.make CMakeFiles/flight_test_scene_script.dir/src/scripts/flight_test_scene.c.i
.PHONY : src/scripts/flight_test_scene.c.i

src/scripts/flight_test_scene.s: src/scripts/flight_test_scene.c.s
.PHONY : src/scripts/flight_test_scene.s

# target to generate assembly for a file
src/scripts/flight_test_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_test_scene_script.dir/build.make CMakeFiles/flight_test_scene_script.dir/src/scripts/flight_test_scene.c.s
.PHONY : src/scripts/flight_test_scene.c.s

src/scripts/logo_scene.o: src/scripts/logo_scene.c.o
.PHONY : src/scripts/logo_scene.o

# target to build an object file
src/scripts/logo_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logo_scene_script.dir/build.make CMakeFiles/logo_scene_script.dir/src/scripts/logo_scene.c.o
.PHONY : src/scripts/logo_scene.c.o

src/scripts/logo_scene.i: src/scripts/logo_scene.c.i
.PHONY : src/scripts/logo_scene.i

# target to preprocess a source file
src/scripts/logo_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logo_scene_script.dir/build.make CMakeFiles/logo_scene_script.dir/src/scripts/logo_scene.c.i
.PHONY : src/scripts/logo_scene.c.i

src/scripts/logo_scene.s: src/scripts/logo_scene.c.s
.PHONY : src/scripts/logo_scene.s

# target to generate assembly for a file
src/scripts/logo_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logo_scene_script.dir/build.make CMakeFiles/logo_scene_script.dir/src/scripts/logo_scene.c.s
.PHONY : src/scripts/logo_scene.c.s

src/scripts/scene_selector_scene.o: src/scripts/scene_selector_scene.c.o
.PHONY : src/scripts/scene_selector_scene.o

# target to build an object file
src/scripts/scene_selector_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_selector_scene_script.dir/build.make CMakeFiles/scene_selector_scene_script.dir/src/scripts/scene_selector_scene.c.o
.PHONY : src/scripts/scene_selector_scene.c.o

src/scripts/scene_selector_scene.i: src/scripts/scene_selector_scene.c.i
.PHONY : src/scripts/scene_selector_scene.i

# target to preprocess a source file
src/scripts/scene_selector_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_selector_scene_script.dir/build.make CMakeFiles/scene_selector_scene_script.dir/src/scripts/scene_selector_scene.c.i
.PHONY : src/scripts/scene_selector_scene.c.i

src/scripts/scene_selector_scene.s: src/scripts/scene_selector_scene.c.s
.PHONY : src/scripts/scene_selector_scene.s

# target to generate assembly for a file
src/scripts/scene_selector_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene_selector_scene_script.dir/build.make CMakeFiles/scene_selector_scene_script.dir/src/scripts/scene_selector_scene.c.s
.PHONY : src/scripts/scene_selector_scene.c.s

src/scripts/thruster_test_scene.o: src/scripts/thruster_test_scene.c.o
.PHONY : src/scripts/thruster_test_scene.o

# target to build an object file
src/scripts/thruster_test_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thruster_test_scene_script.dir/build.make CMakeFiles/thruster_test_scene_script.dir/src/scripts/thruster_test_scene.c.o
.PHONY : src/scripts/thruster_test_scene.c.o

src/scripts/thruster_test_scene.i: src/scripts/thruster_test_scene.c.i
.PHONY : src/scripts/thruster_test_scene.i

# target to preprocess a source file
src/scripts/thruster_test_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thruster_test_scene_script.dir/build.make CMakeFiles/thruster_test_scene_script.dir/src/scripts/thruster_test_scene.c.i
.PHONY : src/scripts/thruster_test_scene.c.i

src/scripts/thruster_test_scene.s: src/scripts/thruster_test_scene.c.s
.PHONY : src/scripts/thruster_test_scene.s

# target to generate assembly for a file
src/scripts/thruster_test_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thruster_test_scene_script.dir/build.make CMakeFiles/thruster_test_scene_script.dir/src/scripts/thruster_test_scene.c.s
.PHONY : src/scripts/thruster_test_scene.c.s

src/system/ai.o: src/system/ai.c.o
.PHONY : src/system/ai.o

# target to build an object file
src/system/ai.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/src/system/ai.c.o
.PHONY : src/system/ai.c.o

src/system/ai.i: src/system/ai.c.i
.PHONY : src/system/ai.i

# target to preprocess a source file
src/system/ai.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/src/system/ai.c.i
.PHONY : src/system/ai.c.i

src/system/ai.s: src/system/ai.c.s
.PHONY : src/system/ai.s

# target to generate assembly for a file
src/system/ai.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/src/system/ai.c.s
.PHONY : src/system/ai.c.s

src/system/camera.o: src/system/camera.c.o
.PHONY : src/system/camera.o

# target to build an object file
src/system/camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera_system.dir/build.make CMakeFiles/camera_system.dir/src/system/camera.c.o
.PHONY : src/system/camera.c.o

src/system/camera.i: src/system/camera.c.i
.PHONY : src/system/camera.i

# target to preprocess a source file
src/system/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera_system.dir/build.make CMakeFiles/camera_system.dir/src/system/camera.c.i
.PHONY : src/system/camera.c.i

src/system/camera.s: src/system/camera.c.s
.PHONY : src/system/camera.s

# target to generate assembly for a file
src/system/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera_system.dir/build.make CMakeFiles/camera_system.dir/src/system/camera.c.s
.PHONY : src/system/camera.c.s

src/system/collision.o: src/system/collision.c.o
.PHONY : src/system/collision.o

# target to build an object file
src/system/collision.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/collision.dir/build.make CMakeFiles/collision.dir/src/system/collision.c.o
.PHONY : src/system/collision.c.o

src/system/collision.i: src/system/collision.c.i
.PHONY : src/system/collision.i

# target to preprocess a source file
src/system/collision.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/collision.dir/build.make CMakeFiles/collision.dir/src/system/collision.c.i
.PHONY : src/system/collision.c.i

src/system/collision.s: src/system/collision.c.s
.PHONY : src/system/collision.s

# target to generate assembly for a file
src/system/collision.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/collision.dir/build.make CMakeFiles/collision.dir/src/system/collision.c.s
.PHONY : src/system/collision.c.s

src/system/control.o: src/system/control.c.o
.PHONY : src/system/control.o

# target to build an object file
src/system/control.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/src/system/control.c.o
.PHONY : src/system/control.c.o

src/system/control.i: src/system/control.c.i
.PHONY : src/system/control.i

# target to preprocess a source file
src/system/control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/src/system/control.c.i
.PHONY : src/system/control.c.i

src/system/control.s: src/system/control.c.s
.PHONY : src/system/control.s

# target to generate assembly for a file
src/system/control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/src/system/control.c.s
.PHONY : src/system/control.c.s

src/system/gamepad.o: src/system/gamepad.c.o
.PHONY : src/system/gamepad.o

# target to build an object file
src/system/gamepad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamepad.dir/build.make CMakeFiles/gamepad.dir/src/system/gamepad.c.o
.PHONY : src/system/gamepad.c.o

src/system/gamepad.i: src/system/gamepad.c.i
.PHONY : src/system/gamepad.i

# target to preprocess a source file
src/system/gamepad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamepad.dir/build.make CMakeFiles/gamepad.dir/src/system/gamepad.c.i
.PHONY : src/system/gamepad.c.i

src/system/gamepad.s: src/system/gamepad.c.s
.PHONY : src/system/gamepad.s

# target to generate assembly for a file
src/system/gamepad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamepad.dir/build.make CMakeFiles/gamepad.dir/src/system/gamepad.c.s
.PHONY : src/system/gamepad.c.s

src/system/input.o: src/system/input.c.o
.PHONY : src/system/input.o

# target to build an object file
src/system/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input.dir/build.make CMakeFiles/input.dir/src/system/input.c.o
.PHONY : src/system/input.c.o

src/system/input.i: src/system/input.c.i
.PHONY : src/system/input.i

# target to preprocess a source file
src/system/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input.dir/build.make CMakeFiles/input.dir/src/system/input.c.i
.PHONY : src/system/input.c.i

src/system/input.s: src/system/input.c.s
.PHONY : src/system/input.s

# target to generate assembly for a file
src/system/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input.dir/build.make CMakeFiles/input.dir/src/system/input.c.s
.PHONY : src/system/input.c.s

src/system/lod.o: src/system/lod.c.o
.PHONY : src/system/lod.o

# target to build an object file
src/system/lod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lod.dir/build.make CMakeFiles/lod.dir/src/system/lod.c.o
.PHONY : src/system/lod.c.o

src/system/lod.i: src/system/lod.c.i
.PHONY : src/system/lod.i

# target to preprocess a source file
src/system/lod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lod.dir/build.make CMakeFiles/lod.dir/src/system/lod.c.i
.PHONY : src/system/lod.c.i

src/system/lod.s: src/system/lod.c.s
.PHONY : src/system/lod.s

# target to generate assembly for a file
src/system/lod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lod.dir/build.make CMakeFiles/lod.dir/src/system/lod.c.s
.PHONY : src/system/lod.c.s

src/system/material.o: src/system/material.c.o
.PHONY : src/system/material.o

# target to build an object file
src/system/material.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/material.dir/build.make CMakeFiles/material.dir/src/system/material.c.o
.PHONY : src/system/material.c.o

src/system/material.i: src/system/material.c.i
.PHONY : src/system/material.i

# target to preprocess a source file
src/system/material.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/material.dir/build.make CMakeFiles/material.dir/src/system/material.c.i
.PHONY : src/system/material.c.i

src/system/material.s: src/system/material.c.s
.PHONY : src/system/material.s

# target to generate assembly for a file
src/system/material.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/material.dir/build.make CMakeFiles/material.dir/src/system/material.c.s
.PHONY : src/system/material.c.s

src/system/memory.o: src/system/memory.c.o
.PHONY : src/system/memory.o

# target to build an object file
src/system/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory.dir/build.make CMakeFiles/memory.dir/src/system/memory.c.o
.PHONY : src/system/memory.c.o

src/system/memory.i: src/system/memory.c.i
.PHONY : src/system/memory.i

# target to preprocess a source file
src/system/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory.dir/build.make CMakeFiles/memory.dir/src/system/memory.c.i
.PHONY : src/system/memory.c.i

src/system/memory.s: src/system/memory.c.s
.PHONY : src/system/memory.s

# target to generate assembly for a file
src/system/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory.dir/build.make CMakeFiles/memory.dir/src/system/memory.c.s
.PHONY : src/system/memory.c.s

src/system/performance.o: src/system/performance.c.o
.PHONY : src/system/performance.o

# target to build an object file
src/system/performance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/performance.dir/build.make CMakeFiles/performance.dir/src/system/performance.c.o
.PHONY : src/system/performance.c.o

src/system/performance.i: src/system/performance.c.i
.PHONY : src/system/performance.i

# target to preprocess a source file
src/system/performance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/performance.dir/build.make CMakeFiles/performance.dir/src/system/performance.c.i
.PHONY : src/system/performance.c.i

src/system/performance.s: src/system/performance.c.s
.PHONY : src/system/performance.s

# target to generate assembly for a file
src/system/performance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/performance.dir/build.make CMakeFiles/performance.dir/src/system/performance.c.s
.PHONY : src/system/performance.c.s

src/system/physics.o: src/system/physics.c.o
.PHONY : src/system/physics.o

# target to build an object file
src/system/physics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/src/system/physics.c.o
.PHONY : src/system/physics.c.o

src/system/physics.i: src/system/physics.c.i
.PHONY : src/system/physics.i

# target to preprocess a source file
src/system/physics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/src/system/physics.c.i
.PHONY : src/system/physics.c.i

src/system/physics.s: src/system/physics.c.s
.PHONY : src/system/physics.s

# target to generate assembly for a file
src/system/physics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/src/system/physics.c.s
.PHONY : src/system/physics.c.s

src/system/thrusters.o: src/system/thrusters.c.o
.PHONY : src/system/thrusters.o

# target to build an object file
src/system/thrusters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thrusters.dir/build.make CMakeFiles/thrusters.dir/src/system/thrusters.c.o
.PHONY : src/system/thrusters.c.o

src/system/thrusters.i: src/system/thrusters.c.i
.PHONY : src/system/thrusters.i

# target to preprocess a source file
src/system/thrusters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thrusters.dir/build.make CMakeFiles/thrusters.dir/src/system/thrusters.c.i
.PHONY : src/system/thrusters.c.i

src/system/thrusters.s: src/system/thrusters.c.s
.PHONY : src/system/thrusters.s

# target to generate assembly for a file
src/system/thrusters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thrusters.dir/build.make CMakeFiles/thrusters.dir/src/system/thrusters.c.s
.PHONY : src/system/thrusters.c.s

src/systems.o: src/systems.c.o
.PHONY : src/systems.o

# target to build an object file
src/systems.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/systems.dir/build.make CMakeFiles/systems.dir/src/systems.c.o
.PHONY : src/systems.c.o

src/systems.i: src/systems.c.i
.PHONY : src/systems.i

# target to preprocess a source file
src/systems.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/systems.dir/build.make CMakeFiles/systems.dir/src/systems.c.i
.PHONY : src/systems.c.i

src/systems.s: src/systems.c.s
.PHONY : src/systems.s

# target to generate assembly for a file
src/systems.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/systems.dir/build.make CMakeFiles/systems.dir/src/systems.c.s
.PHONY : src/systems.c.s

src/ui.o: src/ui.c.o
.PHONY : src/ui.o

# target to build an object file
src/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui.c.o
.PHONY : src/ui.c.o

src/ui.i: src/ui.c.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui.c.i
.PHONY : src/ui.c.i

src/ui.s: src/ui.c.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui.c.s
.PHONY : src/ui.c.s

src/ui_adaptive_controls.o: src/ui_adaptive_controls.c.o
.PHONY : src/ui_adaptive_controls.o

# target to build an object file
src/ui_adaptive_controls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_adaptive_controls.dir/build.make CMakeFiles/ui_adaptive_controls.dir/src/ui_adaptive_controls.c.o
.PHONY : src/ui_adaptive_controls.c.o

src/ui_adaptive_controls.i: src/ui_adaptive_controls.c.i
.PHONY : src/ui_adaptive_controls.i

# target to preprocess a source file
src/ui_adaptive_controls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_adaptive_controls.dir/build.make CMakeFiles/ui_adaptive_controls.dir/src/ui_adaptive_controls.c.i
.PHONY : src/ui_adaptive_controls.c.i

src/ui_adaptive_controls.s: src/ui_adaptive_controls.c.s
.PHONY : src/ui_adaptive_controls.s

# target to generate assembly for a file
src/ui_adaptive_controls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_adaptive_controls.dir/build.make CMakeFiles/ui_adaptive_controls.dir/src/ui_adaptive_controls.c.s
.PHONY : src/ui_adaptive_controls.c.s

src/ui_api.o: src/ui_api.c.o
.PHONY : src/ui_api.o

# target to build an object file
src/ui_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_api.dir/build.make CMakeFiles/ui_api.dir/src/ui_api.c.o
.PHONY : src/ui_api.c.o

src/ui_api.i: src/ui_api.c.i
.PHONY : src/ui_api.i

# target to preprocess a source file
src/ui_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_api.dir/build.make CMakeFiles/ui_api.dir/src/ui_api.c.i
.PHONY : src/ui_api.c.i

src/ui_api.s: src/ui_api.c.s
.PHONY : src/ui_api.s

# target to generate assembly for a file
src/ui_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_api.dir/build.make CMakeFiles/ui_api.dir/src/ui_api.c.s
.PHONY : src/ui_api.c.s

src/ui_components.o: src/ui_components.c.o
.PHONY : src/ui_components.o

# target to build an object file
src/ui_components.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_components.dir/build.make CMakeFiles/ui_components.dir/src/ui_components.c.o
.PHONY : src/ui_components.c.o

src/ui_components.i: src/ui_components.c.i
.PHONY : src/ui_components.i

# target to preprocess a source file
src/ui_components.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_components.dir/build.make CMakeFiles/ui_components.dir/src/ui_components.c.i
.PHONY : src/ui_components.c.i

src/ui_components.s: src/ui_components.c.s
.PHONY : src/ui_components.s

# target to generate assembly for a file
src/ui_components.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_components.dir/build.make CMakeFiles/ui_components.dir/src/ui_components.c.s
.PHONY : src/ui_components.c.s

src/ui_navigation_menu_impl.o: src/ui_navigation_menu_impl.c.o
.PHONY : src/ui_navigation_menu_impl.o

# target to build an object file
src/ui_navigation_menu_impl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/src/ui_navigation_menu_impl.c.o
.PHONY : src/ui_navigation_menu_impl.c.o

src/ui_navigation_menu_impl.i: src/ui_navigation_menu_impl.c.i
.PHONY : src/ui_navigation_menu_impl.i

# target to preprocess a source file
src/ui_navigation_menu_impl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/src/ui_navigation_menu_impl.c.i
.PHONY : src/ui_navigation_menu_impl.c.i

src/ui_navigation_menu_impl.s: src/ui_navigation_menu_impl.c.s
.PHONY : src/ui_navigation_menu_impl.s

# target to generate assembly for a file
src/ui_navigation_menu_impl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/src/ui_navigation_menu_impl.c.s
.PHONY : src/ui_navigation_menu_impl.c.s

src/ui_navigation_menu_render.o: src/ui_navigation_menu_render.c.o
.PHONY : src/ui_navigation_menu_render.o

# target to build an object file
src/ui_navigation_menu_render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/src/ui_navigation_menu_render.c.o
.PHONY : src/ui_navigation_menu_render.c.o

src/ui_navigation_menu_render.i: src/ui_navigation_menu_render.c.i
.PHONY : src/ui_navigation_menu_render.i

# target to preprocess a source file
src/ui_navigation_menu_render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/src/ui_navigation_menu_render.c.i
.PHONY : src/ui_navigation_menu_render.c.i

src/ui_navigation_menu_render.s: src/ui_navigation_menu_render.c.s
.PHONY : src/ui_navigation_menu_render.s

# target to generate assembly for a file
src/ui_navigation_menu_render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_navigation_menu.dir/build.make CMakeFiles/ui_navigation_menu.dir/src/ui_navigation_menu_render.c.s
.PHONY : src/ui_navigation_menu_render.c.s

src/ui_scene.o: src/ui_scene.c.o
.PHONY : src/ui_scene.o

# target to build an object file
src/ui_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_scene.dir/build.make CMakeFiles/ui_scene.dir/src/ui_scene.c.o
.PHONY : src/ui_scene.c.o

src/ui_scene.i: src/ui_scene.c.i
.PHONY : src/ui_scene.i

# target to preprocess a source file
src/ui_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_scene.dir/build.make CMakeFiles/ui_scene.dir/src/ui_scene.c.i
.PHONY : src/ui_scene.c.i

src/ui_scene.s: src/ui_scene.c.s
.PHONY : src/ui_scene.s

# target to generate assembly for a file
src/ui_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_scene.dir/build.make CMakeFiles/ui_scene.dir/src/ui_scene.c.s
.PHONY : src/ui_scene.c.s

third_party/hidapi/mac/hid.o: third_party/hidapi/mac/hid.c.o
.PHONY : third_party/hidapi/mac/hid.o

# target to build an object file
third_party/hidapi/mac/hid.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hidapi.dir/build.make CMakeFiles/hidapi.dir/third_party/hidapi/mac/hid.c.o
.PHONY : third_party/hidapi/mac/hid.c.o

third_party/hidapi/mac/hid.i: third_party/hidapi/mac/hid.c.i
.PHONY : third_party/hidapi/mac/hid.i

# target to preprocess a source file
third_party/hidapi/mac/hid.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hidapi.dir/build.make CMakeFiles/hidapi.dir/third_party/hidapi/mac/hid.c.i
.PHONY : third_party/hidapi/mac/hid.c.i

third_party/hidapi/mac/hid.s: third_party/hidapi/mac/hid.c.s
.PHONY : third_party/hidapi/mac/hid.s

# target to generate assembly for a file
third_party/hidapi/mac/hid.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hidapi.dir/build.make CMakeFiles/hidapi.dir/third_party/hidapi/mac/hid.c.s
.PHONY : third_party/hidapi/mac/hid.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... clean-assets"
	@echo "... compile_assets"
	@echo "... docs"
	@echo "... profile"
	@echo "... run"
	@echo "... run-ctest"
	@echo "... ai"
	@echo "... asset_loader"
	@echo "... assets"
	@echo "... camera_system"
	@echo "... cgame"
	@echo "... collision"
	@echo "... config"
	@echo "... control"
	@echo "... core"
	@echo "... data"
	@echo "... derelict_navigation_scene_script"
	@echo "... flight_test_scene_script"
	@echo "... gamepad"
	@echo "... gpu_resources"
	@echo "... graphics_api"
	@echo "... hidapi"
	@echo "... hud_system"
	@echo "... input"
	@echo "... input_processing"
	@echo "... lod"
	@echo "... logo_scene_script"
	@echo "... look_target"
	@echo "... material"
	@echo "... memory"
	@echo "... performance"
	@echo "... physics"
	@echo "... render_3d"
	@echo "... render_camera"
	@echo "... render_lighting"
	@echo "... render_mesh"
	@echo "... scene_script"
	@echo "... scene_selector_scene_script"
	@echo "... scene_state"
	@echo "... systems"
	@echo "... test_cmake-core_test_components"
	@echo "... test_cmake-core_test_math"
	@echo "... test_cmake-core_test_world"
	@echo "... test_cmake-integration"
	@echo "... test_cmake-performance_test_memory_isolated"
	@echo "... test_cmake-performance_test_memory_perf"
	@echo "... test_cmake-performance_test_performance_critical"
	@echo "... test_cmake-performance_test_performance_simple"
	@echo "... test_cmake-rendering"
	@echo "... test_cmake-ui"
	@echo "... thruster_test_scene_script"
	@echo "... thrusters"
	@echo "... ui"
	@echo "... ui_adaptive_controls"
	@echo "... ui_api"
	@echo "... ui_components"
	@echo "... ui_navigation_menu"
	@echo "... ui_scene"
	@echo "... src/asset_loader/asset_loader_index.o"
	@echo "... src/asset_loader/asset_loader_index.i"
	@echo "... src/asset_loader/asset_loader_index.s"
	@echo "... src/asset_loader/asset_loader_material.o"
	@echo "... src/asset_loader/asset_loader_material.i"
	@echo "... src/asset_loader/asset_loader_material.s"
	@echo "... src/asset_loader/asset_loader_mesh.o"
	@echo "... src/asset_loader/asset_loader_mesh.i"
	@echo "... src/asset_loader/asset_loader_mesh.s"
	@echo "... src/assets.o"
	@echo "... src/assets.i"
	@echo "... src/assets.s"
	@echo "... src/component/look_target.o"
	@echo "... src/component/look_target.i"
	@echo "... src/component/look_target.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/gpu_resources.o"
	@echo "... src/gpu_resources.i"
	@echo "... src/gpu_resources.s"
	@echo "... src/graphics_api.o"
	@echo "... src/graphics_api.i"
	@echo "... src/graphics_api.s"
	@echo "... src/hud_system.o"
	@echo "... src/hud_system.i"
	@echo "... src/hud_system.s"
	@echo "... src/input_processing.o"
	@echo "... src/input_processing.i"
	@echo "... src/input_processing.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render_3d.o"
	@echo "... src/render_3d.i"
	@echo "... src/render_3d.s"
	@echo "... src/render_camera.o"
	@echo "... src/render_camera.i"
	@echo "... src/render_camera.s"
	@echo "... src/render_lighting.o"
	@echo "... src/render_lighting.i"
	@echo "... src/render_lighting.s"
	@echo "... src/render_mesh.o"
	@echo "... src/render_mesh.i"
	@echo "... src/render_mesh.s"
	@echo "... src/scene_script.o"
	@echo "... src/scene_script.i"
	@echo "... src/scene_script.s"
	@echo "... src/scene_state.o"
	@echo "... src/scene_state.i"
	@echo "... src/scene_state.s"
	@echo "... src/scripts/derelict_navigation_scene.o"
	@echo "... src/scripts/derelict_navigation_scene.i"
	@echo "... src/scripts/derelict_navigation_scene.s"
	@echo "... src/scripts/flight_test_scene.o"
	@echo "... src/scripts/flight_test_scene.i"
	@echo "... src/scripts/flight_test_scene.s"
	@echo "... src/scripts/logo_scene.o"
	@echo "... src/scripts/logo_scene.i"
	@echo "... src/scripts/logo_scene.s"
	@echo "... src/scripts/scene_selector_scene.o"
	@echo "... src/scripts/scene_selector_scene.i"
	@echo "... src/scripts/scene_selector_scene.s"
	@echo "... src/scripts/thruster_test_scene.o"
	@echo "... src/scripts/thruster_test_scene.i"
	@echo "... src/scripts/thruster_test_scene.s"
	@echo "... src/system/ai.o"
	@echo "... src/system/ai.i"
	@echo "... src/system/ai.s"
	@echo "... src/system/camera.o"
	@echo "... src/system/camera.i"
	@echo "... src/system/camera.s"
	@echo "... src/system/collision.o"
	@echo "... src/system/collision.i"
	@echo "... src/system/collision.s"
	@echo "... src/system/control.o"
	@echo "... src/system/control.i"
	@echo "... src/system/control.s"
	@echo "... src/system/gamepad.o"
	@echo "... src/system/gamepad.i"
	@echo "... src/system/gamepad.s"
	@echo "... src/system/input.o"
	@echo "... src/system/input.i"
	@echo "... src/system/input.s"
	@echo "... src/system/lod.o"
	@echo "... src/system/lod.i"
	@echo "... src/system/lod.s"
	@echo "... src/system/material.o"
	@echo "... src/system/material.i"
	@echo "... src/system/material.s"
	@echo "... src/system/memory.o"
	@echo "... src/system/memory.i"
	@echo "... src/system/memory.s"
	@echo "... src/system/performance.o"
	@echo "... src/system/performance.i"
	@echo "... src/system/performance.s"
	@echo "... src/system/physics.o"
	@echo "... src/system/physics.i"
	@echo "... src/system/physics.s"
	@echo "... src/system/thrusters.o"
	@echo "... src/system/thrusters.i"
	@echo "... src/system/thrusters.s"
	@echo "... src/systems.o"
	@echo "... src/systems.i"
	@echo "... src/systems.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/ui_adaptive_controls.o"
	@echo "... src/ui_adaptive_controls.i"
	@echo "... src/ui_adaptive_controls.s"
	@echo "... src/ui_api.o"
	@echo "... src/ui_api.i"
	@echo "... src/ui_api.s"
	@echo "... src/ui_components.o"
	@echo "... src/ui_components.i"
	@echo "... src/ui_components.s"
	@echo "... src/ui_navigation_menu_impl.o"
	@echo "... src/ui_navigation_menu_impl.i"
	@echo "... src/ui_navigation_menu_impl.s"
	@echo "... src/ui_navigation_menu_render.o"
	@echo "... src/ui_navigation_menu_render.i"
	@echo "... src/ui_navigation_menu_render.s"
	@echo "... src/ui_scene.o"
	@echo "... src/ui_scene.i"
	@echo "... src/ui_scene.s"
	@echo "... third_party/hidapi/mac/hid.o"
	@echo "... third_party/hidapi/mac/hid.i"
	@echo "... third_party/hidapi/mac/hid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

