/**
 * @file config.c
 * @brief Configuration management system implementation
 */

#include "config.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// Global configuration
static GameConfig g_config;
static bool g_config_initialized = false;

// Default configuration file path
#define CONFIG_FILE_PATH "signal_config.txt"

// Default configuration values
static const GameConfig DEFAULT_CONFIG = {
    .startup_scene = "logo",
    .auto_start = false,
    .master_volume = 0.8f,
    .fullscreen = false,
    .window_width = 1280,
    .window_height = 720
};

bool config_init(void) {
    if (g_config_initialized) {
        return true;
    }
    
    // Start with default configuration
    g_config = DEFAULT_CONFIG;
    
    // Try to load from file
    if (!config_load()) {
        printf("📝 Config: Using default configuration\n");
    }
    
    g_config_initialized = true;
    printf("⚙️  Config system initialized\n");
    return true;
}

void config_shutdown(void) {
    if (!g_config_initialized) {
        return;
    }
    
    // Save configuration on shutdown
    config_save();
    g_config_initialized = false;
    printf("⚙️  Config system shut down\n");
}

GameConfig* config_get(void) {
    if (!g_config_initialized) {
        config_init();
    }
    return &g_config;
}

bool config_save(void) {
    if (!g_config_initialized) {
        return false;
    }
    
    FILE* file = fopen(CONFIG_FILE_PATH, "w");
    if (!file) {
        printf("❌ Config: Failed to open config file for writing: %s\n", CONFIG_FILE_PATH);
        return false;
    }
    
    fprintf(file, "# CGGame Configuration File\n");
    fprintf(file, "# This file is automatically generated and managed\n\n");
    
    fprintf(file, "startup_scene=%s\n", g_config.startup_scene);
    fprintf(file, "auto_start=%s\n", g_config.auto_start ? "true" : "false");
    fprintf(file, "master_volume=%.2f\n", g_config.master_volume);
    fprintf(file, "fullscreen=%s\n", g_config.fullscreen ? "true" : "false");
    fprintf(file, "window_width=%d\n", g_config.window_width);
    fprintf(file, "window_height=%d\n", g_config.window_height);
    
    fclose(file);
    printf("💾 Config: Saved configuration to %s\n", CONFIG_FILE_PATH);
    return true;
}

bool config_load(void) {
    FILE* file = fopen(CONFIG_FILE_PATH, "r");
    if (!file) {
        printf("📝 Config: No config file found at %s\n", CONFIG_FILE_PATH);
        return false;
    }
    
    char line[256];
    int loaded_values = 0;
    
    while (fgets(line, sizeof(line), file)) {
        // Skip comments and empty lines
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\0') {
            continue;
        }
        
        // Remove trailing newline
        char* newline = strchr(line, '\n');
        if (newline) {
            *newline = '\0';
        }
        
        // Parse key=value pairs
        char* equals = strchr(line, '=');
        if (!equals) {
            continue;
        }
        
        *equals = '\0';
        char* key = line;
        char* value = equals + 1;
        
        // Parse specific configuration values
        if (strcmp(key, "startup_scene") == 0) {
            strncpy(g_config.startup_scene, value, sizeof(g_config.startup_scene) - 1);
            g_config.startup_scene[sizeof(g_config.startup_scene) - 1] = '\0';
            loaded_values++;
        } else if (strcmp(key, "auto_start") == 0) {
            g_config.auto_start = (strcmp(value, "true") == 0);
            loaded_values++;
        } else if (strcmp(key, "master_volume") == 0) {
            g_config.master_volume = (float)atof(value);
            loaded_values++;
        } else if (strcmp(key, "fullscreen") == 0) {
            g_config.fullscreen = (strcmp(value, "true") == 0);
            loaded_values++;
        } else if (strcmp(key, "window_width") == 0) {
            g_config.window_width = atoi(value);
            loaded_values++;
        } else if (strcmp(key, "window_height") == 0) {
            g_config.window_height = atoi(value);
            loaded_values++;
        }
    }
    
    fclose(file);
    printf("📝 Config: Loaded %d configuration values from %s\n", loaded_values, CONFIG_FILE_PATH);
    printf("🎯 Startup scene: %s (auto-start: %s)\n", 
           g_config.startup_scene, g_config.auto_start ? "enabled" : "disabled");
    return true;
}

const char* config_get_startup_scene(void) {
    if (!g_config_initialized) {
        config_init();
    }
    return g_config.startup_scene;
}

void config_set_startup_scene(const char* scene_name) {
    if (!g_config_initialized) {
        config_init();
    }
    
    if (scene_name) {
        strncpy(g_config.startup_scene, scene_name, sizeof(g_config.startup_scene) - 1);
        g_config.startup_scene[sizeof(g_config.startup_scene) - 1] = '\0';
        printf("⚙️  Config: Set startup scene to '%s'\n", scene_name);
    }
}

bool config_get_auto_start(void) {
    if (!g_config_initialized) {
        config_init();
    }
    return g_config.auto_start;
}

void config_set_auto_start(bool auto_start) {
    if (!g_config_initialized) {
        config_init();
    }
    
    g_config.auto_start = auto_start;
    printf("⚙️  Config: Set auto-start to %s\n", auto_start ? "enabled" : "disabled");
}
