#ifndef VERSION_H
#define VERSION_H

#define CGAME_VERSION_MAJOR 0
#define CGAME_VERSION_MINOR 2
#define CGAME_VERSION_PATCH 1
#define CGAME_VERSION_STRING "0.2.1"
#define CGAME_BUILD_DATE "2025-07-01"
#define CGAME_BUILD_TIME "17:03:07"

#endif // VERSION_H
