name: Build and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: brew install cairo pkg-config

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Virtual Environment
        run: python3 -m venv .venv

      - name: Install Python Dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Build Project
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cgame-macos
          path: build/cgame

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config libgl1-mesa-dev libx11-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Virtual Environment
        run: python3 -m venv .venv

      - name: Install Python Dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Build Project
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cgame-linux
          path: build/cgame

  build-wasm:
    name: Build (WebAssembly)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.49

      - name: Build Project for WASM
        run: make wasm

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cgame-wasm
          path: build/
          glob: |
            build/cgame.html
            build/cgame.js
            build/cgame.wasm
            build/cgame.data
